version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: netprobe-backend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    container_name: netprobe-frontend

  victim:
    build: ./victim
    ports:
      - "8080:80"
    container_name: netprobe-victim
